version: "3"
services:
  rodrigo_app:    
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - DB_URL=db_mongo
      - EUREKA_SERVICE_URL=eureka-serviceregistry
    volumes:
      - ./todo-list-back:/usr/src/app
      - /usr/src/todo-list-back/app/node_modules
      
  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27014:27017"

  eureka-serviceregistry:
    build: ./eureka-serviceregistry
    ports:
      - "8761:8761"
    tty:
      true
    restart:
      unless-stopped

volumes:
  mongodata: 