version: "3"
services:
  rodrigo_app:    
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - db
      - eureka-serviceregistry
    environment:
      - DB_URL=db_mongo
      - EUREKA_SERVICE_URL=eureka-serviceregistry
      - MY_HOST=rodrigo_app
    volumes:
      - ./todo-list-back:/usr/src/app
      - /usr/src/todo-list-back/app/node_modules
      
  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27014:27017"

  eureka-serviceregistry:
    build: ./eureka-serviceregistry
    ports:
      - "8761:8761"
    restart:
      unless-stopped

  zuul-edgeservice:
    build: ./zuul-edgeservice
    ports:
      - "8080:8080"
    links:
     - eureka-serviceregistry
     - rodrigo_app
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    restart:
      unless-stopped

volumes:
  mongodata: 