version: "3"
services:
  rodrigo_app:    
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - db
      - eureka
    networks:
      - "discovery"
    environment:
      - DB_URL=db_mongo
      - EUREKA_SERVICE_URL=eureka
    volumes:
      - ./todo-list-back:/usr/src/app
      - /usr/src/todo-list-back/app/node_modules
      
  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    networks:
      - "discovery"
    ports:
      - "27014:27017"
      
  eureka:
    image: springcloud/eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - "discovery"
    environment:
      - EUREKA_INSTANCE_PREFERIPADDRESS=true

volumes:
  mongodata:
    
networks:
  discovery: