version: "3"
services:
  rodrigo_app:    
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - DB_URL=db_mysql
    volumes:
      - .:/usr/todo-list-back/src/app
      - /usr/src/todo-list-back/app/node_modules
      
  db:
    image: mysql:5.7
    container_name: db_mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo

volumes:
  db_data: 